1 create search api prototype
holloway-ai/leif pull request #16
Opened 2023-05-29 08:33 UTC by InnaVays

redis index as collection + tests for parsing

2023-05-29 19:21 UTC, iliatimofeev requested changes
** DD**
1. We can add to our collection 10 test documents including the Asq Quran.
2. When we search with query “Вопросы о боге” reference to Ask Quran returned in top 3 documents.
3. That criteria is implemented as unit test and passes
4. Search the exact part in a large document implemented as tests.

**I can't find relevant tests**

2023-05-29 19:21 UTC, iliatimofeev commented on app/api/utils.py
> +def search_by_path(redis_connect, collection_name, tag):
In my opinion, search_by_path should be a part Collection class.

2023-05-29 19:21 UTC, iliatimofeev commented on app/api/utils.py
> +def get_a_key(prefix, document_key, block_num):
In my opinion, get_a_key should be a part Collection class.

2023-05-29 19:21 UTC, iliatimofeev commented on app/api/test_documents.py
> +test_doc = {
Please move test documents to a separate **json** file.
From #15

2023-06-01 10:37 UTC, InnaVays commented on app/api/Depends.py
That is not my file! I did not create it, and have no idea why it exists))

2023-06-01 10:37 UTC, InnaVays commented on app/api/Depends.py
> +class Embedding:
Ok

2023-06-01 15:43 UTC, iliatimofeev commented on app/api/api_v1/endpoints/document.py
>  def list_documents(collection_name: str) -> Any:
Please read this documentation finally
https://fastapi.tiangolo.com/tutorial/dependencies/

2023-06-01 15:45 UTC, iliatimofeev commented on app/api/Depends.py
But it's your code in it. Just rename it.

2023-06-04 15:41 UTC, closed without merging

2023-06-05 10:27 UTC, iliatimofeev reviewed
Redis provides a high-level API to manipulate with [Pydantic](https://pypi.org/project/pydantic/) (which are native to FastAPI) objects, take a look into [blog post](https://redis.com/blog/introducing-redis-om-for-python/) and [documentation](https://redis.io/docs/stack/get-started/tutorials/stack-python/).  Additionally there are some external packages that do it like [pydantic-redis](https://sopherapps.github.io/pydantic-redis/explanation/why-use-orms/). 

- [ ] Please explore that opportunity and consider removing low level querying and encoding in your code.

2023-06-05 10:27 UTC, iliatimofeev commented on app/api/api_v1/endpoints/search.py
> +            #print(f"Search in {collection} ")
Consider moving vector search into Collection class.

 ```python 
 class Collection:
       ....
       def search (self, query:str) ->List[DocumentBlocksSearchResult]
           ...
 ```
       
That will allow us to use search in other places and hide all redis/cohere specifics in one place.