1 create search api prototype
holloway-ai/leif pull request #17
Opened 2023-06-04 15:42 UTC by InnaVays

Questions, Answers, Refs

2023-06-05 11:25 UTC, iliatimofeev commented
Redis provides a high-level API to manipulate with [Pydantic](https://pypi.org/project/pydantic/) (which are native to FastAPI) objects, take a look into [blog post](https://redis.com/blog/introducing-redis-om-for-python/),  [documentation](https://redis.io/docs/stack/get-started/tutorials/stack-python/) and [source code](https://github.com/redis/redis-om-python) .  Additionally there are some external packages that do it like [pydantic-redis](https://sopherapps.github.io/pydantic-redis/explanation/why-use-orms/). 

- [ ] Please explore that opportunity and consider removing low level querying and encoding in your code.  I will reference this suggesion  as **redis_om**.

Please refactor your code into separate modules and classes. `utils.py` intends to be a module for small system utilities, not for putting all your notebook cells into it. `deps.py` is for dependency injection into FastAPI request processing, not for heavy lifting. API implementation files are for implementing API calls; all the heavy lifting should be done in separate modules.


Please refactor your code into separate modules and classes. `utils.py` intends to be a module for small system utilities, not for putting all your notebook cells into it. `deps.py` is for dependency injection into FastAPI request processing, not for heavy lifting. API implementation files are for implementing API calls; all the heavy lifting should be done in separate modules. You have different entities; they should be implemented as classes. Some highly connected entities could be in one module (file), but by default, each entity has one module.

- [ ] `document.py` is for Document class. A document can represent itself as a list (or iterator) of DocumentBlocks. You get a document from the API and just ask it for a DocumentBlocks providing the expected size of the block . 

- [ ] `collection.py` is for `Collection` class that could store and search `DocumentBlock` all the internals of Redis, Cohere, and how exactly you do it. Just a simple interface: add, update, delete, list, search. So when you are implementing an API call, you know nothing about embeddings, or the Redis interface, you just get a list of DocumentBlocks from the document and add them to the collection. Or just get your text query and ask collection for DocumentBlocks

- [ ] `llm.py` currently put functions on question generation and answering on a set of DocumentBlocks into this module.

Test. 

- [ ] Tests **must** be implemented.

2023-06-05 11:49 UTC, iliatimofeev requested changes

2023-06-05 11:49 UTC, iliatimofeev commented on app/api/api_v1/endpoints/document.py
> +    keys = [key for key in collection.connection.scan_iter(f"{collection.name}*")]
Collection class

2023-06-05 11:49 UTC, iliatimofeev commented on app/api/api_v1/endpoints/document.py
> +    pipe = deps.db.connection.pipeline()
Collection class

2023-06-05 11:49 UTC, iliatimofeev commented on app/api/api_v1/endpoints/document.py
> +        blocks = utils.extract_info_blocks(document.render, threshold=utils.THRESHOLD)
Document class

2023-06-05 11:49 UTC, iliatimofeev commented on app/api/api_v1/endpoints/document.py
> +        for i,vector in enumerate(encoded_blocks):
Collection class

2023-06-05 11:49 UTC, iliatimofeev commented on app/api/api_v1/endpoints/document.py
> +            # HSET
redis_om

2023-06-05 11:49 UTC, iliatimofeev commented on app/api/api_v1/endpoints/document.py
> +    for key in keys_to_delete:
Collection class

2023-06-05 11:49 UTC, iliatimofeev commented on app/api/api_v1/endpoints/document.py
> +    blocks = utils.extract_info_blocks(document.render, threshold = utils.THRESHOLD)
Document class return list of DocumentBlocks

2023-06-05 11:49 UTC, iliatimofeev commented on app/api/api_v1/endpoints/document.py
> +    for i,vector in enumerate(encoded_blocks):
Collection class accepts DocumentBlocks

2023-06-05 11:49 UTC, iliatimofeev commented on app/api/api_v1/endpoints/document.py
> +        deps.db.connection.delete(key)
Collection

2023-06-05 11:49 UTC, iliatimofeev commented on app/api/api_v1/endpoints/search.py
> +        query_embedding = utils.encode_blocks(deps.db.embedding, question)
Collection should accept plain text query

2023-06-05 11:49 UTC, iliatimofeev commented on app/api/api_v1/endpoints/search.py
>  @router.get("/", response_model = schemas.SearchResultFull)
```python
@router.get("/{collection_name} ...."
```

I missed that previously.
We should search in the exact collection. Each deployment of Joan will have a unique collection. There is no reason to return documents from other collections, as for now at least.

2023-06-05 11:49 UTC, iliatimofeev commented on app/api/api_v1/endpoints/search.py
> +            redis_search_results = index.search_vectors_knn(redis_connect = deps.db.connection,
Redis_om
Consider to wrap `index.search_vectors_knn` with method that returns list of results Pydantic objects. I guess you can find in the source code of  [redis_om](https://github.com/redis/redis-om-python/blob/87d3a080adf6e9dc2bda1b38204b5b341876f16e/aredis_om/model/model.py#L1371)  examples on how to do it properly.

2023-06-05 11:49 UTC, iliatimofeev commented on app/api/api_v1/endpoints/search.py
> +        for redis_doc in top_results[question]:
Please explore `redis_om` and consider to replace that unreadable `redis_path = redis_dict['path'.encode('utf-8')].decode('utf-8') …` into `block = DocumentBlock.get( result.id)`  and you’ll get access to `block.path` using [redis_om](https://github.com/redis/redis-om-python).

2023-06-05 11:49 UTC, iliatimofeev commented on app/api/deps.py
> +class CollectionDB():
Move to separete file `collection.py`

2023-06-05 11:49 UTC, iliatimofeev commented on app/api/index.py
> +def create_index(redis_connect, index_name, doc_prefix, vector_name, vector_dimensions, distance_metric='IP'):
collection.py

2023-06-05 11:49 UTC, iliatimofeev commented on app/api/utils.py
> +def split_text(text, threshold):
document.py

2023-06-05 11:49 UTC, iliatimofeev commented on app/api/utils.py
> +def generate_questions(prompt, model = "gpt-3.5-turbo", n = 5):
llm.py

2023-06-05 20:09 UTC, iliatimofeev commented on tests/test_api.py
> +from app.api import utils
https://docs.pytest.org/en/6.2.x/fixture.html

2023-06-05 20:11 UTC, iliatimofeev requested changes

2023-06-05 20:11 UTC, iliatimofeev commented on tests/test_api.py
Move lxml tests into unit/test_document.py

2023-06-07 11:12 UTC, InnaVays commented on tests/test_api.py
> +from app.api import utils
Done

2023-06-07 11:23 UTC, InnaVays commented on app/api/deps.py
> +class CollectionDB():
done

2023-06-07 11:37 UTC, InnaVays commented on app/schemas/search.py
>  class SearchResultFull(BaseModel):
done

2023-06-07 12:31 UTC, InnaVays commented on app/api/api_v1/endpoints/document.py
> +    pipe = deps.db.connection.pipeline()
done

2023-06-07 13:15 UTC, InnaVays commented on app/api/api_v1/endpoints/document.py
> +            # HSET
done

2023-06-07 13:15 UTC, InnaVays commented on app/api/api_v1/endpoints/document.py
> +        deps.db.connection.delete(key)
done

2023-06-07 14:48 UTC, InnaVays commented on app/api/index.py
> +def create_index(redis_connect, index_name, doc_prefix, vector_name, vector_dimensions, distance_metric='IP'):
done

2023-06-07 16:20 UTC, InnaVays commented on app/api/api_v1/endpoints/document.py
> +        blocks = utils.extract_info_blocks(document.render, threshold=utils.THRESHOLD)
done

2023-06-07 18:33 UTC, InnaVays commented on app/api/api_v1/endpoints/document.py
> +        for i,vector in enumerate(encoded_blocks):
done

2023-06-07 19:31 UTC, InnaVays commented on tests/test_api.py
done

2023-06-07 20:26 UTC, InnaVays commented on app/api/api_v1/endpoints/document.py
> +    for i,vector in enumerate(encoded_blocks):
done

2023-07-06 21:41 UTC, iliatimofeev commented
1. Redis runs locally in the codespaces container.
2. Cohere and OpenaAI keys are available in codespace
3. Rebased to main
4. Github runs tests on PRs for main. Test results are visible in comments.
5. fixed typo in test_document, and it fails now.

2023-07-07 15:05 UTC, iliatimofeev commented on tests/test_api.py
>  client = TestClient(app)
That should be fixure too

2023-08-10 12:06 UTC, iliatimofeev approved these changes

2023-08-10 12:52 UTC, merged